### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ahstro** [kyasu1/elm-native-ui-maps#3]
`react-native-maps` has some pretty extensive documentation of their components [here](https://github.com/airbnb/react-native-maps#component-api). It's licensed under MIT, so it's probably okay to just move their notes, with some slight modifications, into the Elm doc strings.
Feel free to assign me if you think that's a good idea :)

**Comment by kyasu1** [comment]
Thank you for your offer, I appreciate this. Actually writing documents in English is the hardest part for non native speaker like me ;-)

**Comment by ahstro** [comment]
No problem :) I'll try to get to it this week; getting a new laptop battery any day now, so I'll be able to work on the bus again :)

**Comment by ahstro** [comment]
I'm not really using Elm Native UI anymore, so I'm most likely never going to get to this issue. Not sure if you just want to remove my assignment or close it completely. Sorry for never getting to it ☹️
